[package]
name = "mdreader"
version = "0.1.1"
description = "Markdown Reader"
authors = ["MDReader"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "shell-open", "window-all", "dialog-open", "dialog-save"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
base64 = "0.22"

[features]
custom-protocol = ["tauri/custom-protocol"]
